# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecbrates', '0003_auto_20160202_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecbrate',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ecbrate',
            name='_key',
        ),
        migrations.AlterUniqueTogether(
            name='ecbrate',
            unique_together=set([('date', 'code')]),
        ),
    ]
