# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecbrates', '0004_auto_20160202_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecbrate',
            old_name='code',
            new_name='target',
        ),
        migrations.AddField(
            model_name='ecbrate',
            name='base',
            field=models.CharField(default='EUR', max_length=3, verbose_name='base currency code'),
        ),
        migrations.AlterUniqueTogether(
            name='ecbrate',
            unique_together=set([('date', 'target')]),
        ),
    ]
